// Generated by scripts/vi-locales.mjs sync — do not edit by hand.
import ns_agent_team from './agent-team.json'
import ns_approval from './approval.json'
import ns_chat from './chat.json'
import ns_command from './command.json'
import ns_common from './common.json'
import ns_conversation from './conversation.json'
import ns_cordis from './cordis.json'
import ns_deliverables from './deliverables.json'
import ns_directory_browser from './directory-browser.json'
import ns_documentHtml from './documentHtml.json'
import ns_documentMarkdown from './documentMarkdown.json'
import ns_feedback from './feedback.json'
import ns_goal from './goal.json'
import ns_job from './job.json'
import ns_model from './model.json'
import ns_open_in_app from './open-in-app.json'
import ns_permission_access from './permission.access.json'
import ns_plan from './plan.json'
import ns_pluginManager from './pluginManager.json'
import ns_question from './question.json'
import ns_reference from './reference.json'
import ns_schedule_catalog from './schedule.catalog.json'
import ns_schedule_manager from './schedule.manager.json'
import ns_session_log_download from './session-log-download.json'
import ns_settings from './settings.json'
import ns_settings_account from './settings.account.json'
import ns_settings_agentLoop from './settings.agentLoop.json'
import ns_settings_agentPreset from './settings.agentPreset.json'
import ns_settings_locale from './settings.locale.json'
import ns_settings_models from './settings.models.json'
import ns_settings_permission from './settings.permission.json'
import ns_settings_pluginInventory from './settings.pluginInventory.json'
import ns_settings_plugins from './settings.plugins.json'
import ns_settings_sessionLog from './settings.sessionLog.json'
import ns_settings_shell from './settings.shell.json'
import ns_settings_subagent from './settings.subagent.json'
import ns_settings_theme from './settings.theme.json'
import ns_settings_webSearch from './settings.webSearch.json'
import ns_shortcuts from './shortcuts.json'
import ns_shortcuts_layout from './shortcuts.layout.json'
import ns_sidebar from './sidebar.json'
import ns_sidebarBrowser from './sidebarBrowser.json'
import ns_sidebarCodePreview from './sidebarCodePreview.json'
import ns_sidebarDocumentPreview from './sidebarDocumentPreview.json'
import ns_sidebarExcel from './sidebarExcel.json'
import ns_sidebarFiles from './sidebarFiles.json'
import ns_sidebarImage from './sidebarImage.json'
import ns_sidebarOffice from './sidebarOffice.json'
import ns_sidebarPdf from './sidebarPdf.json'
import ns_sidebarRight from './sidebarRight.json'
import ns_sidebarTerminal from './sidebarTerminal.json'
import ns_skill from './skill.json'
import ns_slash_menu from './slash.menu.json'
import ns_subagent from './subagent.json'
import ns_trajectory from './trajectory.json'
import ns_voice_input from './voice-input.json'
import ns_workflowRun from './workflowRun.json'
import ns_workspace from './workspace.json'

/** Vietnamese dictionaries keyed by the DSH locale namespace they translate. */
export const VI_DICTIONARIES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "agent-team": ns_agent_team,
  "approval": ns_approval,
  "chat": ns_chat,
  "command": ns_command,
  "common": ns_common,
  "conversation": ns_conversation,
  "cordis": ns_cordis,
  "deliverables": ns_deliverables,
  "directory-browser": ns_directory_browser,
  "documentHtml": ns_documentHtml,
  "documentMarkdown": ns_documentMarkdown,
  "feedback": ns_feedback,
  "goal": ns_goal,
  "job": ns_job,
  "model": ns_model,
  "open-in-app": ns_open_in_app,
  "permission.access": ns_permission_access,
  "plan": ns_plan,
  "pluginManager": ns_pluginManager,
  "question": ns_question,
  "reference": ns_reference,
  "schedule.catalog": ns_schedule_catalog,
  "schedule.manager": ns_schedule_manager,
  "session-log-download": ns_session_log_download,
  "settings": ns_settings,
  "settings.account": ns_settings_account,
  "settings.agentLoop": ns_settings_agentLoop,
  "settings.agentPreset": ns_settings_agentPreset,
  "settings.locale": ns_settings_locale,
  "settings.models": ns_settings_models,
  "settings.permission": ns_settings_permission,
  "settings.pluginInventory": ns_settings_pluginInventory,
  "settings.plugins": ns_settings_plugins,
  "settings.sessionLog": ns_settings_sessionLog,
  "settings.shell": ns_settings_shell,
  "settings.subagent": ns_settings_subagent,
  "settings.theme": ns_settings_theme,
  "settings.webSearch": ns_settings_webSearch,
  "shortcuts": ns_shortcuts,
  "shortcuts.layout": ns_shortcuts_layout,
  "sidebar": ns_sidebar,
  "sidebarBrowser": ns_sidebarBrowser,
  "sidebarCodePreview": ns_sidebarCodePreview,
  "sidebarDocumentPreview": ns_sidebarDocumentPreview,
  "sidebarExcel": ns_sidebarExcel,
  "sidebarFiles": ns_sidebarFiles,
  "sidebarImage": ns_sidebarImage,
  "sidebarOffice": ns_sidebarOffice,
  "sidebarPdf": ns_sidebarPdf,
  "sidebarRight": ns_sidebarRight,
  "sidebarTerminal": ns_sidebarTerminal,
  "skill": ns_skill,
  "slash.menu": ns_slash_menu,
  "subagent": ns_subagent,
  "trajectory": ns_trajectory,
  "voice-input": ns_voice_input,
  "workflowRun": ns_workflowRun,
  "workspace": ns_workspace,
}
