#!/usr/bin/env node
/**
 * Maintain the per-namespace Vietnamese dictionaries in src/client/locales/vi.
 *
 *   node scripts/vi-locales.mjs sync   create missing <ns>.json files, regenerate index.ts
 *   node scripts/vi-locales.mjs check [ns…]  diff against the upstream English snapshot (optionally only
 *                                            the listed namespaces); exit 1 on any finding
 *
 * The snapshot is the newest upstream/en-*.json (see scripts/extract-en.mjs).
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compareDicts } from './lib/compare-dicts.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const VI_DIR = join(ROOT, 'src/client/locales/vi')

function latestSnapshot() {
  const files = readdirSync(join(ROOT, 'upstream')).filter((f) => /^en-.+\.json$/.test(f)).sort()
  if (files.length === 0) throw new Error('no upstream/en-*.json snapshot; run scripts/extract-en.mjs first')
  const file = files.at(-1)
  return { file, en: JSON.parse(readFileSync(join(ROOT, 'upstream', file), 'utf8')) }
}

function readVi() {
  const vi = {}
  for (const f of readdirSync(VI_DIR).filter((f) => f.endsWith('.json'))) {
    vi[f.slice(0, -'.json'.length)] = JSON.parse(readFileSync(join(VI_DIR, f), 'utf8'))
  }
  return vi
}

function sync() {
  const { en } = latestSnapshot()
  let created = 0
  for (const ns of Object.keys(en)) {
    const file = join(VI_DIR, `${ns}.json`)
    if (!existsSync(file)) {
      writeFileSync(file, '{}\n')
      created++
    }
  }
  const namespaces = Object.keys(readVi()).sort()
  const ident = (ns) => `ns_${ns.replace(/[^A-Za-z0-9]/g, '_')}`
  const lines = [
    '// Generated by scripts/vi-locales.mjs sync — do not edit by hand.',
    ...namespaces.map((ns) => `import ${ident(ns)} from './${ns}.json'`),
    '',
    '/** Vietnamese dictionaries keyed by the DSH locale namespace they translate. */',
    'export const VI_DICTIONARIES: Readonly<Record<string, Readonly<Record<string, string>>>> = {',
    ...namespaces.map((ns) => `  ${JSON.stringify(ns)}: ${ident(ns)},`),
    '}',
    '',
  ]
  writeFileSync(join(VI_DIR, 'index.ts'), lines.join('\n'))
  console.log(`vi: ${namespaces.length} namespaces (${created} new files), index.ts regenerated`)
}

function check(only) {
  const { file, en: all } = latestSnapshot()
  const pick = (dicts) => only.length === 0 ? dicts : Object.fromEntries(Object.entries(dicts).filter(([ns]) => only.includes(ns)))
  const en = pick(all)
  const report = compareDicts(en, pick(readVi()))
  const pct = ((report.translated / report.total) * 100).toFixed(1)
  console.log(`vi vs ${file}: ${report.translated}/${report.total} translated (${pct}%)`)
  let failed = false
  for (const [label, items] of [['missing', report.missing], ['empty', report.empty], ['extra (not upstream)', report.extra], ['placeholder mismatch', report.placeholder]]) {
    if (items.length === 0) continue
    failed = true
    console.log(`  ${label}: ${items.length}`)
    for (const id of items.slice(0, 20)) console.log(`    ${id}`)
    if (items.length > 20) console.log(`    … ${items.length - 20} more`)
  }
  process.exitCode = failed ? 1 : 0
}

const command = process.argv[2]
if (command === 'sync') sync()
else if (command === 'check') check(process.argv.slice(3))
else {
  console.error('usage: vi-locales.mjs <sync|check>')
  process.exitCode = 2
}
